package com.tju.zq.mapper;

import com.tju.zq.model.ItemOrder;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ItemOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_item_order
     *
     * @mbggenerated Sun Jun 21 14:52:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    List<ItemOrder> list(ItemOrder item);
    int count(ItemOrder item);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_item_order
     *
     * @mbggenerated Sun Jun 21 14:52:19 CST 2020
     */
    int insert(ItemOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_item_order
     *
     * @mbggenerated Sun Jun 21 14:52:19 CST 2020
     */
    ItemOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_item_order
     *
     * @mbggenerated Sun Jun 21 14:52:19 CST 2020
     */
    List<ItemOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_item_order
     *
     * @mbggenerated Sun Jun 21 14:52:19 CST 2020
     */
    int updateByPrimaryKey(ItemOrder record);
}