package com.tju.zq.mapper;

import com.tju.zq.model.Provider;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    List<Provider> list(Provider item);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    int insert(Provider record);

    int count(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    Provider selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    List<Provider> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    int updateByPrimaryKey(Provider record);
}