package com.tju.zq.mapper;

import com.tju.zq.model.ProviderItem;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProviderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_item
     *
     * @mbggenerated Sat Jun 20 18:09:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    int count(ProviderItem record);

    List<ProviderItem> list(ProviderItem item);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_item
     *
     * @mbggenerated Sat Jun 20 18:09:21 CST 2020
     */
    int insert(ProviderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_item
     *
     * @mbggenerated Sat Jun 20 18:09:21 CST 2020
     */
    ProviderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_item
     *
     * @mbggenerated Sat Jun 20 18:09:21 CST 2020
     */
    List<ProviderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_item
     *
     * @mbggenerated Sat Jun 20 18:09:21 CST 2020
     */
    int updateByPrimaryKey(ProviderItem record);
}