package com.tju.zq.mapper;

import com.tju.zq.model.ProviderOrder;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProviderOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_order
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    int count(ProviderOrder record);
    List<ProviderOrder> list(ProviderOrder item);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_order
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    int insert(ProviderOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_order
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    ProviderOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_order
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    List<ProviderOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tju_provider_order
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    int updateByPrimaryKey(ProviderOrder record);
}