package com.tju.zq.model;

public class Provider extends BaseObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.id
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.name
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.level
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.address
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.person
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private String person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.phone
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider.bank
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    private String bank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.id
     *
     * @return the value of tju_provider.id
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.id
     *
     * @param id the value for tju_provider.id
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.name
     *
     * @return the value of tju_provider.name
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.name
     *
     * @param name the value for tju_provider.name
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.level
     *
     * @return the value of tju_provider.level
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.level
     *
     * @param level the value for tju_provider.level
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.address
     *
     * @return the value of tju_provider.address
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.address
     *
     * @param address the value for tju_provider.address
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.person
     *
     * @return the value of tju_provider.person
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.person
     *
     * @param person the value for tju_provider.person
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setPerson(String person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.phone
     *
     * @return the value of tju_provider.phone
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.phone
     *
     * @param phone the value for tju_provider.phone
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider.bank
     *
     * @return the value of tju_provider.bank
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider.bank
     *
     * @param bank the value for tju_provider.bank
     *
     * @mbggenerated Sat Jun 20 12:03:44 CST 2020
     */
    public void setBank(String bank) {
        this.bank = bank;
    }
}