package com.tju.zq.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class ProviderOrder extends BaseObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.id
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.name
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.count
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.price
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.total
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private String total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.sdes
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private String sdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.time
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date time;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date mintime;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date maxtime;

    public Date getMintime() {
        return mintime;
    }

    public void setMintime(Date mintime) {
        this.mintime = mintime;
    }

    public Date getMaxtime() {
        return maxtime;
    }

    public void setMaxtime(Date maxtime) {
        this.maxtime = maxtime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tju_provider_order.provider
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    private String provider;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.id
     *
     * @return the value of tju_provider_order.id
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.id
     *
     * @param id the value for tju_provider_order.id
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.name
     *
     * @return the value of tju_provider_order.name
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.name
     *
     * @param name the value for tju_provider_order.name
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.count
     *
     * @return the value of tju_provider_order.count
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.count
     *
     * @param count the value for tju_provider_order.count
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.price
     *
     * @return the value of tju_provider_order.price
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.price
     *
     * @param price the value for tju_provider_order.price
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.total
     *
     * @return the value of tju_provider_order.total
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.total
     *
     * @param total the value for tju_provider_order.total
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setTotal(String total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.sdes
     *
     * @return the value of tju_provider_order.sdes
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public String getSdes() {
        return sdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.sdes
     *
     * @param sdes the value for tju_provider_order.sdes
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setSdes(String sdes) {
        this.sdes = sdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.time
     *
     * @return the value of tju_provider_order.time
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.time
     *
     * @param time the value for tju_provider_order.time
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
    public void setTime(String time) {
        this.time = new Date(time);
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tju_provider_order.provider
     *
     * @return the value of tju_provider_order.provider
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tju_provider_order.provider
     *
     * @param provider the value for tju_provider_order.provider
     *
     * @mbggenerated Sat Jun 20 23:53:12 CST 2020
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }
}